export const initialList1 = [
  {
    id: 2,
    docEntry: 2,
    docNum: 2,
    postDate: "9/16/2022 12:00:00 AM",
    warehouse: "GEN01",
    itemCode: "CS00018",
    itemName: "Cadmium Bolt Nut with Double Washer 12 X 50 mm",
    plannedQty: "1.000000",
    objectType: "202",
    cardCode: "CD00002",
    poLines: [
      {
        id: 0,
        docEntry: 2,
        lineNum: 0,
        itemCode: "CS00001",
        itemName: "Putting Patty",
        plannedQty: "1.000000",
        warehouse: "CNS01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "NOS",
      },
      {
        id: 1,
        docEntry: 2,
        lineNum: 1,
        itemCode: "CS00002",
        itemName: "Zinc Spray (Cold Galvanizing)",
        plannedQty: "1.000000",
        warehouse: "GEN01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "CAN",
      },
    ],
  },
  {
    id: 6,
    docEntry: 6,
    docNum: 6,
    postDate: "12/16/2022 12:00:00 AM",
    warehouse: "GEN01",
    itemCode: "CS00018",
    itemName: "Cadmium Bolt Nut with Double Washer 12 X 50 mm",
    plannedQty: "1.000000",
    objectType: "202",
    cardCode: "CD00001",
    poLines: [
      {
        id: 0,
        docEntry: 6,
        lineNum: 0,
        itemCode: "CS00001",
        itemName: "Putting Patty",
        plannedQty: "1.000000",
        warehouse: "CNS01",
        ocrCode: "CST02",
        project: "LINDE",
        uomCode: "NOS",
      },
      {
        id: 1,
        docEntry: 6,
        lineNum: 1,
        itemCode: "CS00002",
        itemName: "Zinc Spray (Cold Galvanizing)",
        plannedQty: "1.000000",
        warehouse: "GEN01",
        ocrCode: "CST02",
        project: "LINDE",
        uomCode: "CAN",
      },
    ],
  },
  {
    id: 7,
    docEntry: 7,
    docNum: 7,
    postDate: "12/27/2022 12:00:00 AM",
    warehouse: "GEN01",
    itemCode: "S1015_300851300_M9502",
    itemName: "ROLLER TBLE SUPPORT",
    plannedQty: "1.000000",
    objectType: "202",
    cardCode: "CD00029",
    poLines: [
      {
        id: 0,
        docEntry: 7,
        lineNum: 0,
        itemCode: "RW00781",
        itemName: "ISMB 250_Len 5.5-6.5 Mtrs_IS 2062 E250A/BR",
        plannedQty: "800.800000",
        warehouse: "GEN01",
        ocrCode: "CST02",
        project: "LINDE",
        uomCode: "KGS",
      },
      {
        id: 1,
        docEntry: 7,
        lineNum: 1,
        itemCode: "RW00781",
        itemName: "ISMB 250_Len 5.5-6.5 Mtrs_IS 2062 E250A/BR",
        plannedQty: "1474.000000",
        warehouse: "GEN01",
        ocrCode: "CST02",
        project: "LINDE",
        uomCode: "KGS",
      },
      {
        id: 2,
        docEntry: 7,
        lineNum: 2,
        itemCode: "RW00781",
        itemName: "ISMB 250_Len 5.5-6.5 Mtrs_IS 2062 E250A/BR",
        plannedQty: "78.125000",
        warehouse: "GEN01",
        ocrCode: "CST02",
        project: "LINDE",
        uomCode: "KGS",
      },
    ],
  },
  {
    id: 8,
    docEntry: 8,
    docNum: 8,
    postDate: "12/27/2022 12:00:00 AM",
    warehouse: "GEN01",
    itemCode: "CS00018",
    itemName: "Cadmium Bolt Nut with Double Washer 12 X 50 mm",
    plannedQty: "1.000000",
    objectType: "202",
    cardCode: "CD00002",
    poLines: [
      {
        id: 0,
        docEntry: 8,
        lineNum: 0,
        itemCode: "CS00001",
        itemName: "Putting Patty",
        plannedQty: "1.000000",
        warehouse: "CNS01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "NOS",
      },
      {
        id: 1,
        docEntry: 8,
        lineNum: 1,
        itemCode: "CS00002",
        itemName: "Zinc Spray (Cold Galvanizing)",
        plannedQty: "1.000000",
        warehouse: "GEN01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "CAN",
      },
    ],
  },
  {
    id: 9,
    docEntry: 9,
    docNum: 9,
    postDate: "1/3/2023 12:00:00 AM",
    warehouse: "GEN01",
    itemCode: "CS00018",
    itemName: "Cadmium Bolt Nut with Double Washer 12 X 50 mm",
    plannedQty: "1.000000",
    objectType: "202",
    cardCode: "",
    poLines: [
      {
        id: 0,
        docEntry: 9,
        lineNum: 0,
        itemCode: "CS00001",
        itemName: "Putting Patty",
        plannedQty: "1.000000",
        warehouse: "GEN01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "NOS",
      },
      {
        id: 1,
        docEntry: 9,
        lineNum: 1,
        itemCode: "CS00002",
        itemName: "Zinc Spray (Cold Galvanizing)",
        plannedQty: "1.000000",
        warehouse: "GEN01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "CAN",
      },
    ],
  },
];
export const initialList2 = [
  {
    id: 6,
    docEntry: 6,
    docNum: 6,
    postDate: "12/16/2022 12:00:00 AM",
    warehouse: "GEN01",
    itemCode: "CS00018",
    itemName: "Cadmium Bolt Nut with Double Washer 12 X 50 mm",
    plannedQty: "1.000000",
    objectType: "202",
    cardCode: "CD00001",
    poLines: [
      {
        id: 61,
        docEntry: 6,
        lineNum: 0,
        itemCode: "CS00001",
        itemName: "Putting Patty",
        plannedQty: "1.000000",
        warehouse: "CNS01",
        ocrCode: "CST02",
        project: "LINDE",
        uomCode: "NOS",
      },
      {
        id: 62,
        docEntry: 6,
        lineNum: 1,
        itemCode: "CS00002",
        itemName: "Zinc Spray (Cold Galvanizing)",
        plannedQty: "1.000000",
        warehouse: "GEN01",
        ocrCode: "CST02",
        project: "LINDE",
        uomCode: "CAN",
      },
    ],
  },
  {
    id: 7,
    docEntry: 7,
    docNum: 7,
    postDate: "12/27/2022 12:00:00 AM",
    warehouse: "GEN01",
    itemCode: "S1015_300851300_M9502",
    itemName: "ROLLER TBLE SUPPORT",
    plannedQty: "1.000000",
    objectType: "202",
    cardCode: "CD00029",
    poLines: [
      {
        id: 71,
        docEntry: 7,
        lineNum: 0,
        itemCode: "RW00781",
        itemName: "ISMB 250_Len 5.5-6.5 Mtrs_IS 2062 E250A/BR",
        plannedQty: "800.800000",
        warehouse: "GEN01",
        ocrCode: "CST02",
        project: "LINDE",
        uomCode: "KGS",
      },
      {
        id: 72,
        docEntry: 7,
        lineNum: 1,
        itemCode: "RW00781",
        itemName: "ISMB 250_Len 5.5-6.5 Mtrs_IS 2062 E250A/BR",
        plannedQty: "1474.000000",
        warehouse: "GEN01",
        ocrCode: "CST02",
        project: "LINDE",
        uomCode: "KGS",
      },
    ],
  },
  {
    id: 8,
    docEntry: 8,
    docNum: 8,
    postDate: "12/27/2022 12:00:00 AM",
    warehouse: "GEN01",
    itemCode: "CS00018",
    itemName: "Cadmium Bolt Nut with Double Washer 12 X 50 mm",
    plannedQty: "1.000000",
    objectType: "202",
    cardCode: "CD00002",
    poLines: [
      {
        id: 81,
        docEntry: 8,
        lineNum: 0,
        itemCode: "CS00001",
        itemName: "Putting Patty",
        plannedQty: "1.000000",
        warehouse: "CNS01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "NOS",
      },
      {
        id: 82,
        docEntry: 8,
        lineNum: 1,
        itemCode: "CS00002",
        itemName: "Zinc Spray (Cold Galvanizing)",
        plannedQty: "1.000000",
        warehouse: "GEN01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "CAN",
      },
    ],
  },
  {
    id: 9,
    docEntry: 9,
    docNum: 9,
    postDate: "1/3/2023 12:00:00 AM",
    warehouse: "GEN01",
    itemCode: "CS00018",
    itemName: "Cadmium Bolt Nut with Double Washer 12 X 50 mm",
    plannedQty: "1.000000",
    objectType: "202",
    cardCode: "",
    poLines: [
      {
        id: 91,
        docEntry: 9,
        lineNum: 0,
        itemCode: "CS00001",
        itemName: "Putting Patty",
        plannedQty: "1.000000",
        warehouse: "GEN01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "NOS",
      },
      {
        id: 92,
        docEntry: 9,
        lineNum: 1,
        itemCode: "CS00002",
        itemName: "Zinc Spray (Cold Galvanizing)",
        plannedQty: "1.000000",
        warehouse: "GEN01",
        ocrCode: "CST01",
        project: "LINDE",
        uomCode: "CAN",
      },
    ],
  },
];
export const warehouseAPI = [
  {
    id: "ALP02",
    whsCode: "01",
    whsName: "General Warehouse",
  },
  {
    id: "ALP01",
    whsCode: "ALP01",
    whsName: "Aluminum and Pipes",
  },
  {
    id: "BFG01",
    whsCode: "BFG01",
    whsName: "Black FG",
  },
  {
    id: "CNS01",
    whsCode: "CNS01",
    whsName: "Consumables",
  },
  {
    id: "CYL01",
    whsCode: "CYL01",
    whsName: "Cylinders",
  },
  {
    id: "EMCY01",
    whsCode: "EMCY01",
    whsName: "EMPLY CYLENDERS",
  },
  {
    id: "EWIP01",
    whsCode: "EWIP01",
    whsName: "WIP Wiz Equipment Fabrication",
  },
  {
    id: "FFG01",
    whsCode: "FFG01",
    whsName: "Final FG",
  },
  {
    id: "GDW01",
    whsCode: "GDW01",
    whsName: "Godown",
  },
  {
    id: "GEN01",
    whsCode: "GEN01",
    whsName: "General Store",
  },
  {
    id: "JB01",
    whsCode: "JB01",
    whsName: "Job-Work",
  },
  {
    id: "MTL01",
    whsCode: "MTL01",
    whsName: "Precious metals",
  },
];

export const seriesAPI = [
  {
    id: 19,
    series: 19,
    seriesName: "G2021-22",
  },
  {
    id: 122,
    series: 122,
    seriesName: "R2021-22",
  },
  {
    id: 123,
    series: 123,
    seriesName: "C2021-22",
  },
  {
    id: 124,
    series: 124,
    seriesName: "G2022-23",
  },
  {
    id: 125,
    series: 125,
    seriesName: "R2022-23",
  },
  {
    id: 126,
    series: 126,
    seriesName: "C2022-23",
  },
];
